# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/BDv1/BDv1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BDv1 || ORIG_REF_NAME==BDv1} -quiet] -quiet

# IP: bd/BDv1/ip/BDv1_processing_system7_0_0/BDv1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BDv1_processing_system7_0_0 || ORIG_REF_NAME==BDv1_processing_system7_0_0} -quiet] -quiet

# IP: bd/BDv1/ip/BDv1_axi_timer_0_0/BDv1_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BDv1_axi_timer_0_0 || ORIG_REF_NAME==BDv1_axi_timer_0_0} -quiet] -quiet

# IP: bd/BDv1/ip/BDv1_axi_timer_0_1/BDv1_axi_timer_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BDv1_axi_timer_0_1 || ORIG_REF_NAME==BDv1_axi_timer_0_1} -quiet] -quiet

# IP: bd/BDv1/ip/BDv1_xbar_0/BDv1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BDv1_xbar_0 || ORIG_REF_NAME==BDv1_xbar_0} -quiet] -quiet

# IP: bd/BDv1/ip/BDv1_auto_pc_0/BDv1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BDv1_auto_pc_0 || ORIG_REF_NAME==BDv1_auto_pc_0} -quiet] -quiet

# IP: bd/BDv1/ip/BDv1_ps7_0_axi_periph_0/BDv1_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BDv1_ps7_0_axi_periph_0 || ORIG_REF_NAME==BDv1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/BDv1/ip/BDv1_rst_ps7_0_100M_0/BDv1_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BDv1_rst_ps7_0_100M_0 || ORIG_REF_NAME==BDv1_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/BDv1/ip/BDv1_xlconcat_0_0/BDv1_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BDv1_xlconcat_0_0 || ORIG_REF_NAME==BDv1_xlconcat_0_0} -quiet] -quiet

# XDC: bd/BDv1/BDv1_ooc.xdc
