# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Mi/SEP2024_local/JuegoRitmoFPGA/src/Vivado/ProjectoV02/ProjectoV02.srcs/sources_1/bd/BDv1/ip/BDv1_processing_system7_0_0/BDv1_processing_system7_0_0.xci
# IP: The module: 'BDv1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Mi/SEP2024_local/JuegoRitmoFPGA/src/Vivado/ProjectoV02/ProjectoV02.srcs/sources_1/bd/BDv1/ip/BDv1_processing_system7_0_0/BDv1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'BDv1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/Mi/SEP2024_local/JuegoRitmoFPGA/src/Vivado/ProjectoV02/ProjectoV02.srcs/sources_1/bd/BDv1/ip/BDv1_processing_system7_0_0/BDv1_processing_system7_0_0.xci
# IP: The module: 'BDv1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Mi/SEP2024_local/JuegoRitmoFPGA/src/Vivado/ProjectoV02/ProjectoV02.srcs/sources_1/bd/BDv1/ip/BDv1_processing_system7_0_0/BDv1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'BDv1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
