# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Mi/SEP2024_local/JuegoRitmoFPGA/src/Vivado/ProjectoV02/ProjectoV02.srcs/sources_1/bd/BDv1/ip/BDv1_axi_timer_0_1/BDv1_axi_timer_0_1.xci
# IP: The module: 'BDv1_axi_timer_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Mi/SEP2024_local/JuegoRitmoFPGA/src/Vivado/ProjectoV02/ProjectoV02.srcs/sources_1/bd/BDv1/ip/BDv1_axi_timer_0_1/BDv1_axi_timer_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'BDv1_axi_timer_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Mi/SEP2024_local/JuegoRitmoFPGA/src/Vivado/ProjectoV02/ProjectoV02.srcs/sources_1/bd/BDv1/ip/BDv1_axi_timer_0_1/BDv1_axi_timer_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BDv1_axi_timer_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Mi/SEP2024_local/JuegoRitmoFPGA/src/Vivado/ProjectoV02/ProjectoV02.srcs/sources_1/bd/BDv1/ip/BDv1_axi_timer_0_1/BDv1_axi_timer_0_1.xci
# IP: The module: 'BDv1_axi_timer_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Mi/SEP2024_local/JuegoRitmoFPGA/src/Vivado/ProjectoV02/ProjectoV02.srcs/sources_1/bd/BDv1/ip/BDv1_axi_timer_0_1/BDv1_axi_timer_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'BDv1_axi_timer_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Mi/SEP2024_local/JuegoRitmoFPGA/src/Vivado/ProjectoV02/ProjectoV02.srcs/sources_1/bd/BDv1/ip/BDv1_axi_timer_0_1/BDv1_axi_timer_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BDv1_axi_timer_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
